# example netlify.toml
[build]
  command = "gatsby build"
  functions = "netlify/functions"
  publish = "public"

## redirects for ubiquity site pages to fulcrum site pages


  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  [[redirects]]
    from = "https://about.newprairiepress.org/*"
    to = "https://newprairiepress.org:splat"
    status = 301
